# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ImageOpenTransitionExampleProject' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

#pod 'ImageOpenTransition', :path => '../'
pod 'ImageOpenTransition'

  # Pods for ImageOpenTransitionExampleProject

  target 'ImageOpenTransitionExampleProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ImageOpenTransitionExampleProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
